
package com.some.service.finance;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "financeSupport", targetNamespace = "http://some.com/service/finance", wsdlLocation = "http://192.168.2.103:7001/SomeSupportSF/financeSupport?WSDL")
public class FinanceSupport
    extends Service
{

    private final static URL FINANCESUPPORT_WSDL_LOCATION;
    private final static WebServiceException FINANCESUPPORT_EXCEPTION;
    private final static QName FINANCESUPPORT_QNAME = new QName("http://some.com/service/finance", "financeSupport");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.2.103:7001/SomeSupportSF/financeSupport?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FINANCESUPPORT_WSDL_LOCATION = url;
        FINANCESUPPORT_EXCEPTION = e;
    }

    public FinanceSupport() {
        super(__getWsdlLocation(), FINANCESUPPORT_QNAME);
    }

    public FinanceSupport(WebServiceFeature... features) {
        super(__getWsdlLocation(), FINANCESUPPORT_QNAME, features);
    }

    public FinanceSupport(URL wsdlLocation) {
        super(wsdlLocation, FINANCESUPPORT_QNAME);
    }

    public FinanceSupport(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FINANCESUPPORT_QNAME, features);
    }

    public FinanceSupport(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinanceSupport(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SomeSupport
     */
    @WebEndpoint(name = "SomeSupportPort")
    public SomeSupport getSomeSupportPort() {
        return super.getPort(new QName("http://some.com/service/finance", "SomeSupportPort"), SomeSupport.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SomeSupport
     */
    @WebEndpoint(name = "SomeSupportPort")
    public SomeSupport getSomeSupportPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://some.com/service/finance", "SomeSupportPort"), SomeSupport.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FINANCESUPPORT_EXCEPTION!= null) {
            throw FINANCESUPPORT_EXCEPTION;
        }
        return FINANCESUPPORT_WSDL_LOCATION;
    }

}
