
package com.some.service.finance;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SomeSupport", targetNamespace = "http://some.com/service/finance")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SomeSupport {


    /**
     * 
     * @return
     *     returns java.util.List<com.some.service.finance.CacheManagerInformation>
     */
    @WebMethod(action = "urn:getCacheManagerInformation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCacheManagerInformation", targetNamespace = "http://some.com/service/finance", className = "com.some.service.finance.GetCacheManagerInformation")
    @ResponseWrapper(localName = "getCacheManagerInformationResponse", targetNamespace = "http://some.com/service/finance", className = "com.some.service.finance.GetCacheManagerInformationResponse")
    @Action(input = "urn:getCacheManagerInformation", output = "http://some.com/service/finance/SomeSupport/getCacheManagerInformationResponse")
    public List<CacheManagerInformation> getCacheManagerInformation();

}
